---
# tasks file for role-docker-install
- name: apt update
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: install docker and it's dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
