version: '3.7'
services:

  jenkins:
    build: .
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    container_name: jenkins
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: ncdev22
    volumes:
      - ./configs/:/jenkins_configs
      - ./jenkins_home:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock

