---
 - hosts: ci
   become: false
   
   tasks:  
   - name: RUN DOCKER-COMPOSE FOR INSTALL JENKINS
     shell: git clone https://github.com/neizmirasego/ncdevopsschool22.git && cd ~/ncdevopsschool22/jenkins-install && sudo docker-compose up -d
