version: '3.7'

services:

  webapp:
    container_name: flask
    build: .
    user: root
    restart: always
    ports:
      - '5000:80'
    volumes:
      - .:/app
    networks:
      - network

networks:
  network:
    driver: bridge
  
