---
# tasks file for install_apache2
 

- name: CREATE NEW DIR FOR REGISTRY
  file:
    path: "{{ item }}" 
    state: directory
    owner: "{{ user }}"
    mode: '0775'
  with_items:
    - ./docker-registry/auth
    - ./docker-registry/repo  
    - ./docker-registry/certs  
          
- name: COPY CERT TO SERVER
  template:
    src: "{{ item }}" 
    dest: "./docker-registry/auth"
  with_fileglob: 
    - files/domain.key
    - files/domain.crt


- name: INSTALL HTPASSWD
  apt: 
    name: "{{ packages }}" 
    update_cache: yes 
    state: latest
  vars:
    packages:
    - apache2-utils
    
- name: CREATE PASSWORD FOR REGISTRY 
  shell: htpasswd -Bbn "{{ user_registry }}" "{{ pass_registry }}" > ./docker-registry/auth/htpasswd
 
- name: COPY DOCKER-COMPOSE FILE TO SERVER
  template:
    src: "files/docker-compose.yml.j2"
    dest: "./docker-registry/docker-compose.yml"

- name: RUN DOCKER-COMPOSE
  shell: cd ./docker-registry && docker-compose up -d
          
   
      


