name: Create instances using Terraform

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Terraform Format
      run: terraform fmt -check
  
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
