name: Deploy to GCP

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
   
    # Setup key
    - name: Setup key
      #run: |
          #ssh-keygen -f ~/.ssh/key -N ""
          #cat ~/.ssh/key.pub | ssh root@34.118.122.9 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && chmod -R go= ~/.ssh && cat >> ~/.ssh/authorized_keys"

      run: | 
           mkdir "$HOME/.ssh"
           echo "${{ secrets.KEY }}" > "$HOME/.ssh/id_rsa"
           chmod 600 "$HOME/.ssh/id_rsa"
           
      # Install Ansible to Github-actions
    - name: Install Ansible to Github-actions server
      run: | 
           sudo apt update
           sudo apt install software-properties-common
           sudo add-apt-repository --yes --update ppa:ansible/ansible
           sudo apt install ansible
           
     # Install Docker to GCP    
    - name:  Install Docker to GCP instances
      run: | 
           cd "./ansible"
           ansible all -m ping -u "root"
           ansible-playbook playbook.yml
           
      # Install Jenkins to GCP      
    - name:  Install Jenkins to GCP instance
      run: | 
           cd "./ansible"
           ansible-playbook playbook-jenkins.yml
           
           
